import type { Category } from "./sites";

type Seed = [domainOrUrl: string, name: string];

// Extra safe-by-default domains. These are curated public sites, official docs,
// museums, education portals, creative tools, sports/food resources, and media.
// The main site builder still runs the global safety filter over every entry.
export const SAFE_DOMAIN_PACK: Record<Category, Seed[]> = {
  knowledge: [
    ["openstax.org", "OpenStax"], ["oercommons.org", "OER Commons"], ["merlot.org", "MERLOT"],
    ["saylor.org", "Saylor Academy"], ["academicearth.org", "Academic Earth"], ["worldcat.org", "WorldCat"],
    ["doaj.org", "Directory of Open Access Journals"], ["core.ac.uk", "CORE"], ["openlibrary.org", "Open Library"],
    ["standardebooks.org", "Standard Ebooks"], ["librivox.org", "LibriVox"], ["wikibooks.org", "Wikibooks"],
    ["wikiversity.org", "Wikiversity"], ["wikisource.org", "Wikisource"], ["wikivoyage.org", "Wikivoyage"],
    ["wiktionary.org", "Wiktionary"], ["howstuffworks.com", "HowStuffWorks"], ["mentalfloss.com", "Mental Floss"],
    ["snopes.com", "Snopes"], ["factcheck.org", "FactCheck.org"], ["ourworldindata.org", "Our World in Data"],
    ["gapminder.org", "Gapminder"], ["data.worldbank.org", "World Bank Data"], ["data.gov", "Data.gov"],
    ["eurostat.ec.europa.eu", "Eurostat"], ["unesco.org", "UNESCO"], ["un.org", "United Nations"],
    ["who.int/data", "WHO Data"], ["imf.org", "IMF"], ["oecd.org", "OECD"],
    ["loc.gov/maps", "Library of Congress Maps"], ["davidrumsey.com", "David Rumsey Map Collection"],
    ["oldmapsonline.org", "Old Maps Online"], ["perseus.tufts.edu", "Perseus Digital Library"],
    ["sacred-texts.com", "Internet Sacred Text Archive"], ["poetryfoundation.org", "Poetry Foundation"],
    ["poets.org", "Poets.org"], ["royalroad.com", "Royal Road"], ["goodreads.com", "Goodreads"],
    ["bookshop.org", "Bookshop"], ["libbyapp.com", "Libby"], ["overdrive.com", "OverDrive"],
    ["classcentral.com", "Class Central"], ["brilliant.org", "Brilliant"], ["codecademy.com", "Codecademy"],
    ["freecodecamp.org", "freeCodeCamp"], ["futureme.org", "FutureMe"], ["exploratorium.edu", "Exploratorium"],
  ],
  science: [
    ["phys.org", "Phys.org"], ["eurekalert.org", "EurekAlert"], ["researchgate.net", "ResearchGate"],
    ["orcid.org", "ORCID"], ["crossref.org", "Crossref"], ["openalex.org", "OpenAlex"],
    ["pubmed.ncbi.nlm.nih.gov", "PubMed"], ["ncbi.nlm.nih.gov", "NCBI"], ["genome.gov", "Genome.gov"],
    ["ensembl.org", "Ensembl"], ["rcsb.org", "Protein Data Bank"], ["uniprot.org", "UniProt"],
    ["chemistryworld.com", "Chemistry World"], ["periodictable.com", "PeriodicTable.com"], ["ptable.com", "Ptable"],
    ["wolfram.com", "Wolfram"], ["desmos.com", "Desmos"], ["geogebra.org", "GeoGebra"],
    ["nrich.maths.org", "NRICH"], ["mathworld.wolfram.com", "MathWorld"], ["oeis.org", "OEIS"],
    ["planetary.org", "The Planetary Society"], ["heavens-above.com", "Heavens Above"], ["stellarium-web.org", "Stellarium Web"],
    ["sky-map.org", "Sky Map"], ["apod.nasa.gov", "Astronomy Picture of the Day"], ["earthobservatory.nasa.gov", "NASA Earth Observatory"],
    ["eol.org", "Encyclopedia of Life"], ["inaturalist.org", "iNaturalist"], ["ebird.org", "eBird"],
    ["gbif.org", "GBIF"], ["marinespecies.org", "WoRMS"], ["paleobiodb.org", "Paleobiology Database"],
    ["volcano.si.edu", "Global Volcanism Program"], ["earthquake.usgs.gov", "USGS Earthquakes"], ["weather.gov", "National Weather Service"],
    ["metoffice.gov.uk", "Met Office"], ["ecmwf.int", "ECMWF"], ["copernicus.eu", "Copernicus"],
    ["esa.int/Science_Exploration", "ESA Science"], ["science.nasa.gov", "NASA Science"],
  ],
  gaming: [
    ["minecraft.net", "Minecraft"], ["minecraft.wiki", "Minecraft Wiki"], ["terraria.org", "Terraria"],
    ["stardewvalley.net", "Stardew Valley"], ["factorio.com", "Factorio"], ["satisfactorygame.com", "Satisfactory"],
    ["kerbalspaceprogram.com", "Kerbal Space Program"], ["play.date", "Playdate"], ["analogue.co", "Analogue"],
    ["retroachievements.org", "RetroAchievements"], ["moby.games", "MobyGames"], ["igdb.com", "IGDB"],
    ["rawg.io", "RAWG"], ["gamebanana.com", "GameBanana"], ["mod.io", "mod.io"],
    ["planetminecraft.com", "Planet Minecraft"], ["minecraftmaps.com", "Minecraft Maps"], ["openttd.org", "OpenTTD"],
    ["0ad.com", "0 A.D."], ["supertuxkart.net", "SuperTuxKart"], ["minetest.net", "Minetest"],
    ["openra.net", "OpenRA"], ["wesnoth.org", "Battle for Wesnoth"], ["play0ad.com", "0 A.D. Play"],
    ["boardgamearena.com", "Board Game Arena"], ["tabletopia.com", "Tabletopia"], ["boardgamegeek.com", "BoardGameGeek"],
    ["rpggeek.com", "RPGGeek"], ["videogamegeek.com", "VideoGameGeek"], ["chessable.com", "Chessable"],
    ["puzzlescript.net", "PuzzleScript"], ["lexaloffle.com", "Lexaloffle"], ["pico-8-edu.com", "PICO-8 EDU"],
    ["construct.net", "Construct"], ["gdevelop.io", "GDevelop"], ["bitsy.org", "Bitsy"],
    ["twinery.org", "Twine"], ["godotengine.org", "Godot"], ["love2d.org", "LÖVE"],
  ],
  dev: [
    ["docs.github.com", "GitHub Docs"], ["docs.gitlab.com", "GitLab Docs"], ["git-scm.com", "Git"],
    ["learn.microsoft.com", "Microsoft Learn"], ["developer.apple.com", "Apple Developer"], ["developers.google.com", "Google Developers"],
    ["web.dev", "web.dev"], ["chrome.dev", "Chrome for Developers"], ["firefox-source-docs.mozilla.org", "Firefox Source Docs"],
    ["node.green", "Node Green"], ["compat-table.github.io", "ECMAScript Compat Table"], ["tc39.es", "TC39"],
    ["npmjs.com", "npm"], ["yarnpkg.com", "Yarn"], ["pnpm.io", "pnpm"], ["jsr.io", "JSR"],
    ["crates.io", "crates.io"], ["docs.rs", "docs.rs"], ["pkg.go.dev", "Go Packages"],
    ["pypi.org", "PyPI"], ["packagist.org", "Packagist"], ["rubygems.org", "RubyGems"],
    ["nuget.org", "NuGet"], ["mvnrepository.com", "Maven Repository"], ["docker.com", "Docker"],
    ["hub.docker.com", "Docker Hub"], ["kubernetes.io", "Kubernetes"], ["helm.sh", "Helm"],
    ["terraform.io", "Terraform"], ["opentofu.org", "OpenTofu"], ["ansible.com", "Ansible"],
    ["nginx.org", "nginx"], ["apache.org", "Apache"], ["sqlitebrowser.org", "DB Browser for SQLite"],
    ["dbdiagram.io", "dbdiagram.io"], ["drawdb.app", "drawDB"], ["mermaid.js.org", "Mermaid"],
    ["plantuml.com", "PlantUML"], ["exercism.org", "Exercism"], ["codewars.com", "Codewars"],
    ["leetcode.com", "LeetCode"], ["hackerrank.com", "HackerRank"], ["codeforces.com", "Codeforces"],
    ["projecteuler.net", "Project Euler"], ["adventofcode.com", "Advent of Code"], ["roadmap.sh", "roadmap.sh"],
    ["refactoring.guru", "Refactoring Guru"], ["patterns.dev", "Patterns.dev"], ["12factor.net", "The Twelve-Factor App"],
  ],
  art: [
    ["rijksmuseum.nl", "Rijksmuseum"], ["getty.edu", "Getty"], ["nga.gov/open-access-images", "NGA Open Access"],
    ["artic.edu", "Art Institute of Chicago"], ["whitney.org", "Whitney Museum"], ["sfmoma.org", "SFMOMA"],
    ["vam.ac.uk", "Victoria and Albert Museum"], ["cooperhewitt.org", "Cooper Hewitt"], ["designmuseum.org", "Design Museum"],
    ["walkerart.org", "Walker Art Center"], ["serpentinegalleries.org", "Serpentine"], ["nga.gov", "National Gallery of Art"],
    ["europeana.eu", "Europeana"], ["digitalcollections.nypl.org", "NYPL Digital Collections"], ["wellcomecollection.org", "Wellcome Collection"],
    ["publicdomainreview.org", "Public Domain Review"], ["letterformarchive.org", "Letterform Archive"], ["typewolf.com", "Typewolf"],
    ["fontsinuse.com", "Fonts In Use"], ["eyeondesign.aiga.org", "Eye on Design"], ["itsnicethat.com", "It's Nice That"],
    ["creativeboom.com", "Creative Boom"], ["colossal.com", "Colossal"], ["design-milk.com", "Design Milk"],
    ["awwwards.com", "Awwwards"], ["thefwa.com", "The FWA"], ["siteinspire.com", "siteInspire"],
    ["godly.website", "Godly"], ["minimal.gallery", "Minimal Gallery"], ["land-book.com", "Land-book"],
    ["uimovement.com", "UI Movement"], ["mobbin.com", "Mobbin"], ["lottiefiles.com", "LottieFiles"],
  ],
  music: [
    ["boilerroom.tv", "Boiler Room"], ["kcrw.com", "KCRW"], ["wfmu.org", "WFMU"], ["kdhx.org", "KDHX"],
    ["nts.live", "NTS Live"], ["radiooooo.com", "Radiooooo"], ["radioparadise.com", "Radio Paradise"],
    ["classicalmpr.org", "Classical MPR"], ["medici.tv", "Medici.tv"], ["imslp.org", "IMSLP"],
    ["musescore.org", "MuseScore Open Source"], ["flat.io", "Flat"], ["noteflight.com", "Noteflight"],
    ["soundation.com", "Soundation"], ["ampedstudio.com", "Amped Studio"], ["onlinesequencer.net", "Online Sequencer"],
    ["drumbit.app", "drumbit"], ["typedrummer.com", "Typedrummer"], ["patatap.com", "Patatap"],
    ["learningmusic.ableton.com", "Ableton Learning Music"], ["learningsynths.ableton.com", "Ableton Learning Synths"],
    ["musiclab.chromeexperiments.com", "Chrome Music Lab"], ["songexploder.net", "Song Exploder"], ["aquariumdrunkard.com", "Aquarium Drunkard"],
    ["stereogum.com", "Stereogum"], ["thequietus.com", "The Quietus"], ["residentadvisor.net", "Resident Advisor"],
  ],
  tools: [
    ["ray.so", "Ray.so"], ["snappify.com", "Snappify"], ["shots.so", "Shots"], ["screen.studio", "Screen Studio"],
    ["jitter.video", "Jitter"], ["rive.app", "Rive"], ["spline.design", "Spline"], ["unicorn.studio", "Unicorn Studio"],
    ["uiverse.io", "UIverse"], ["magicpattern.design", "MagicPattern"], ["haikei.app", "Haikei"], ["fffuel.co", "fffuel"],
    ["getwaves.io", "Get Waves"], ["svgator.com", "SVGator"], ["svgrepo.com", "SVG Repo"], ["heroicons.com", "Heroicons"],
    ["lucide.dev", "Lucide"], ["simpleicons.org", "Simple Icons"], ["iconoir.com", "Iconoir"], ["tabler.io/icons", "Tabler Icons"],
    ["responsively.app", "Responsively"], ["browserstack.com", "BrowserStack"], ["pagespeed.web.dev", "PageSpeed Insights"],
    ["gtmetrix.com", "GTmetrix"], ["webpagetest.org", "WebPageTest"], ["validator.w3.org", "W3C Validator"],
    ["jsonlint.com", "JSONLint"], ["jwt.io", "JWT.io"], ["crontab.guru", "crontab guru"], ["raycast.com", "Raycast"],
    ["alfredapp.com", "Alfred"], ["shottr.cc", "Shottr"], ["cleanshot.com", "CleanShot"], ["kapwing.com", "Kapwing"],
    ["ezgif.com", "EZGIF"], ["cloudconvert.com", "CloudConvert"], ["convertio.co", "Convertio"], ["photopea.com", "Photopea"],
  ],
  fun: [
    ["littlealchemy.com", "Little Alchemy"], ["quickdraw.withgoogle.com", "Quick, Draw!"], ["semantle.com", "Semantle"],
    ["worldle.teuteuf.fr", "Worldle"], ["travle.earth", "Travle"], ["flagle.io", "Flagle"], ["timeguessr.com", "TimeGuessr"],
    ["wikitrivia.tomjwatson.com", "WikiTrivia"], ["wikigame.com", "The Wiki Game"], ["neal.fun", "neal.fun"],
    ["neal.fun/deep-sea", "The Deep Sea"], ["neal.fun/space-elevator", "Space Elevator"], ["neal.fun/size-of-space", "Size of Space"],
    ["neal.fun/infinite-craft", "Infinite Craft"], ["neal.fun/password-game", "The Password Game"], ["neal.fun/speed", "Speed"],
    ["sandspiel.club", "Sandspiel"], ["weavesilk.com", "Silk"], ["thisissand.com", "Thisissand"], ["typatone.com", "Typatone"],
    ["bongo.cat", "Bongo Cat"], ["koalastothemax.com", "Koalas to the Max"], ["zoomquilt.org", "Zoomquilt"],
    ["zoomquilt2.com", "Zoomquilt 2"], ["29a.ch/sandbox/2011/neonflames", "Neon Flames"], ["mrdoob.com", "Mr.doob"],
    ["experiments.withgoogle.com", "Experiments with Google"], ["artsandculture.google.com/experiment", "Google Arts Experiments"],
  ],
  video: [
    ["peacocktv.com", "Peacock"], ["paramountplus.com", "Paramount+"], ["disneyplus.com", "Disney+"], ["hulu.com", "Hulu"],
    ["netflix.com", "Netflix"], ["max.com", "Max"], ["primevideo.com", "Prime Video"], ["apple.com/apple-tv-plus", "Apple TV+"],
    ["criterionchannel.com", "Criterion Channel"], ["kanopy.com", "Kanopy"], ["hoopladigital.com", "Hoopla"], ["plex.tv", "Plex"],
    ["ted.com", "TED"], ["pbs.org/video", "PBS Video"], ["npr.org/podcasts-and-shows", "NPR Shows"], ["dw.com/en/media-center", "DW Media Center"],
    ["arte.tv", "ARTE"], ["nfb.ca", "National Film Board"], ["loc.gov/film-and-videos", "Library of Congress Video"], ["europeanfilmgateway.eu", "European Film Gateway"],
  ],
  news: [
    ["theconversation.com", "The Conversation"], ["vox.com", "Vox"], ["statnews.com", "STAT"], ["undark.org", "Undark"],
    ["restofworld.org", "Rest of World"], ["platformer.news", "Platformer"], ["themarkup.org", "The Markup"], ["404media.co", "404 Media"],
    ["semafor.com", "Semafor"], ["grid.news", "Grid News"], ["csmonitor.com", "Christian Science Monitor"], ["time.com", "TIME"],
    ["nationalreview.com", "National Review"], ["newstatesman.com", "New Statesman"], ["newscientist.com", "New Scientist"], ["scientificamerican.com", "Scientific American"],
    ["wired.com/category/science", "WIRED Science"], ["arstechnica.com/science", "Ars Technica Science"], ["techmeme.com", "Techmeme"], ["morningbrew.com", "Morning Brew"],
  ],
  sports: [
    ["theathletic.com", "The Athletic"], ["bleacherreport.com", "Bleacher Report"], ["cbssports.com", "CBS Sports"], ["nbcsports.com", "NBC Sports"],
    ["foxsports.com", "FOX Sports"], ["si.com", "Sports Illustrated"], ["theplayerstribune.com", "The Players' Tribune"], ["transfermarkt.com", "Transfermarkt"],
    ["fbref.com", "FBref"], ["basketball-reference.com", "Basketball Reference"], ["baseball-reference.com", "Baseball Reference"], ["pro-football-reference.com", "Pro Football Reference"],
    ["hockey-reference.com", "Hockey Reference"], ["stathead.com", "Stathead"], ["fivethirtyeight.com/sports", "FiveThirtyEight Sports"], ["racing-reference.info", "Racing Reference"],
    ["world.rugby", "World Rugby"], ["worldaquatics.com", "World Aquatics"], ["ironman.com", "IRONMAN"], ["trailrunner.com", "Trail Runner"],
    ["outsideonline.com", "Outside"], ["cyclingnews.com", "Cyclingnews"], ["pinkbike.com", "Pinkbike"], ["climbing.com", "Climbing"],
  ],
  food: [
    ["seriouseats.com", "Serious Eats"], ["cookscountry.com", "Cook's Country"], ["milkstreet.com", "Milk Street"], ["cooking.nytimes.com", "NYT Cooking"],
    ["simplyrecipes.com", "Simply Recipes"], ["recipetineats.com", "RecipeTin Eats"], ["loveandlemons.com", "Love and Lemons"], ["cookieandkate.com", "Cookie and Kate"],
    ["101cookbooks.com", "101 Cookbooks"], ["damndelicious.net", "Damn Delicious"], ["halfbakedharvest.com", "Half Baked Harvest"], ["sallysbakingaddiction.com", "Sally's Baking Addiction"],
    ["kingarthurbaking.com/recipes", "King Arthur Recipes"], ["theperfectloaf.com", "The Perfect Loaf"], ["breadtopia.com", "Breadtopia"], ["freshloaf.com", "The Fresh Loaf"],
    ["baristahustle.com", "Barista Hustle"], ["homegrounds.co", "Homegrounds"], ["beanpoet.com", "Bean Poet"], ["teaformeplease.com", "Tea for Me Please"],
    ["thespruceeats.com/cocktails-4162710", "Spruce Eats Drinks"], ["diffordsguide.com", "Difford's Guide"], ["punchdrink.com", "PUNCH"], ["winefolly.com", "Wine Folly"],
  ],
};